-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20251115132440_3934bfd3-34c9-4b6a-9db1-9860d9dccd27.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20251115132440_3934bfd3_34c9_4b6a_9db1_9860d9dcc(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20251115132440_3934bfd3-34c9-4b6a-9db1-9860d9dccd27.sql',
      'statements', 1
    );
  END IF;

  -- from 20251115132440_3934bfd3-34c9-4b6a-9db1-9860d9dccd27.sql:133
  INSERT INTO public.neighborhoods (name, slug, boundary_points, center_lat, center_lng, description) VALUES
  ('South End', 'south-end', 
   '[[35.2144, -80.8542], [35.2144, -80.8342], [35.2244, -80.8342], [35.2244, -80.8542]]'::jsonb,
   35.2194, -80.8442, 'Trendy neighborhood with breweries and restaurants'),
   
  ('Uptown', 'uptown',
   '[[35.2200, -80.8500], [35.2200, -80.8380], [35.2300, -80.8380], [35.2300, -80.8500]]'::jsonb,
   35.2250, -80.8440, 'Downtown Charlotte with rooftop bars and fine dining'),
   
  ('Plaza Midwood', 'plaza-midwood',
   '[[35.2000, -80.8250], [35.2000, -80.8150], [35.2100, -80.8150], [35.2100, -80.8250]]'::jsonb,
   35.2050, -80.8200, 'Eclectic arts district with dive bars and live music'),
   
  ('NoDa', 'noda',
   '[[35.2450, -80.8050], [35.2450, -80.7950], [35.2550, -80.7950], [35.2550, -80.8050]]'::jsonb,
   35.2500, -80.8000, 'Arts and entertainment district with galleries and breweries'),
   
  ('Camp North End', 'camp-north-end',
   '[[35.2350, -80.8350], [35.2350, -80.8250], [35.2450, -80.8250], [35.2450, -80.8350]]'::jsonb,
   35.2400, -80.8300, 'Creative campus with food halls and markets');

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20251115132440_3934bfd3_34c9_4b6a_9db1_9860d9dcc(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20251115132440_3934bfd3_34c9_4b6a_9db1_9860d9dcc(boolean) TO authenticated, service_role;
