-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20251120195239_8e157352-8f2f-4e62-9cff-25ffe6ebacaa.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20251120195239_8e157352_8f2f_4e62_9cff_25ffe6eba(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20251120195239_8e157352-8f2f-4e62-9cff-25ffe6ebacaa.sql',
      'statements', 1
    );
  END IF;

  -- from 20251120195239_8e157352-8f2f-4e62-9cff-25ffe6ebacaa.sql:6
  UPDATE public.deals 
  SET venue_address = CASE 
    WHEN venue_name = 'Rooftop 210' THEN '210 E Trade St, Charlotte, NC 28202'
    WHEN venue_name = 'Pin House' THEN '222 S Tryon St, Charlotte, NC 28202'
    WHEN venue_name = 'Wooden Robot' THEN '1440 S Tryon St, Charlotte, NC 28203'
    WHEN venue_name = 'Ink N Ivy' THEN '222 S Church St, Charlotte, NC 28202'
    WHEN venue_name = 'Fitzgerald''s' THEN '1301 Central Ave, Charlotte, NC 28205'
    WHEN venue_name = 'The Punch Room' THEN '128 N Tryon St, Charlotte, NC 28202'
    WHEN venue_name = 'NoDa Brewing' THEN '2921 N Tryon St, Charlotte, NC 28206'
    WHEN venue_name = 'Camp North End' THEN '300 Camp Rd, Charlotte, NC 28206'
    WHEN venue_name = 'Wooden Robot Brewery' THEN '1440 S Tryon St, Charlotte, NC 28203'
    ELSE venue_address
  END
  WHERE venue_address IS NULL;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20251120195239_8e157352_8f2f_4e62_9cff_25ffe6eba(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20251120195239_8e157352_8f2f_4e62_9cff_25ffe6eba(boolean) TO authenticated, service_role;
