-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260820092350_69d27ca5-7a06-4e3e-a18d-d90c6ddb5bdc.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260820092350_69d27ca5_7a06_4e3e_a18d_d90c6ddb5(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260820092350_69d27ca5-7a06-4e3e-a18d-d90c6ddb5bdc.sql',
      'statements', 1
    );
  END IF;

  -- from 20260820092350_69d27ca5-7a06-4e3e-a18d-d90c6ddb5bdc.sql:12
  UPDATE public.profiles SET discoverable = true WHERE discoverable IS NULL;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260820092350_69d27ca5_7a06_4e3e_a18d_d90c6ddb5(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260820092350_69d27ca5_7a06_4e3e_a18d_d90c6ddb5(boolean) TO authenticated, service_role;
