-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260819231915_5be903fd-f504-4757-91de-9decaa6512ac.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260819231915_5be903fd_f504_4757_91de_9decaa651(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260819231915_5be903fd-f504-4757-91de-9decaa6512ac.sql',
      'statements', 1
    );
  END IF;

  -- from 20260819231915_5be903fd-f504-4757-91de-9decaa6512ac.sql:21
  INSERT INTO public.email_queue_thresholds (metric, warn_value, crit_value) VALUES
    ('queue_depth', 50, 250),
    ('processing_lag_seconds', 300, 900),
    ('dlq_depth', 1, 10)
  ON CONFLICT (metric) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260819231915_5be903fd_f504_4757_91de_9decaa651(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260819231915_5be903fd_f504_4757_91de_9decaa651(boolean) TO authenticated, service_role;
