-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260725112454_31dc6fe6-ea16-4ed5-b504-02c328d23985.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260725112454_31dc6fe6_ea16_4ed5_b504_02c328d23(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260725112454_31dc6fe6-ea16-4ed5-b504-02c328d23985.sql',
      'statements', 1
    );
  END IF;

  -- from 20260725112454_31dc6fe6-ea16-4ed5-b504-02c328d23985.sql:44
  INSERT INTO public.retention_settings (id) VALUES (true)
  ON CONFLICT (id) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260725112454_31dc6fe6_ea16_4ed5_b504_02c328d23(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260725112454_31dc6fe6_ea16_4ed5_b504_02c328d23(boolean) TO authenticated, service_role;
