-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260820120218_ccf5b39b-0a81-4263-bbc4-3eb404da959f.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260820120218_ccf5b39b_0a81_4263_bbc4_3eb404da9(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260820120218_ccf5b39b-0a81-4263-bbc4-3eb404da959f.sql',
      'statements', 1
    );
  END IF;

  -- from 20260820120218_ccf5b39b-0a81-4263-bbc4-3eb404da959f.sql:8
  UPDATE public.realtime_guard_allowlist
  SET allow_replica_identity_full = true,
      note = note || ' — full old-row payloads acknowledged (needed for realtime column filters)'
  WHERE table_name IN ('user_favorites', 'user_connections', 'search_history', 'venue_reviews')
    AND allow_replica_identity_full = false;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260820120218_ccf5b39b_0a81_4263_bbc4_3eb404da9(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260820120218_ccf5b39b_0a81_4263_bbc4_3eb404da9(boolean) TO authenticated, service_role;
