-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822045457_ea2e3b6b-77bc-43b2-99ce-e81b09812fcb.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822045457_ea2e3b6b_77bc_43b2_99ce_e81b09812(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822045457_ea2e3b6b-77bc-43b2-99ce-e81b09812fcb.sql',
      'statements', 1
    );
  END IF;

  -- from 20260822045457_ea2e3b6b-77bc-43b2-99ce-e81b09812fcb.sql:5
  INSERT INTO public.realtime_guard_allowlist (table_name, sensitivity, note, allow_replica_identity_full)
  VALUES
    ('messages', 'private', 'Direct messages; RLS scopes rows to sender/recipient.', false),
    ('email_send_log', 'private', 'Admin-only email delivery log; RLS restricts reads to admins.', false)
  ON CONFLICT (table_name) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822045457_ea2e3b6b_77bc_43b2_99ce_e81b09812(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822045457_ea2e3b6b_77bc_43b2_99ce_e81b09812(boolean) TO authenticated, service_role;
