-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260824091823_fb38790d-09b6-4b62-a6de-53e7df831ae9.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260824091823_fb38790d_09b6_4b62_a6de_53e7df831(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260824091823_fb38790d-09b6-4b62-a6de-53e7df831ae9.sql',
      'statements', 1
    );
  END IF;

  -- from 20260824091823_fb38790d-09b6-4b62-a6de-53e7df831ae9.sql:2
  UPDATE public.realtime_guard_allowlist
  SET sensitivity = 'public',
      note = 'Heartbeat only (profile id + created/updated flag + timestamp). All authenticated users can read because /social surfaces every signed-up user.'
  WHERE table_name = 'profile_pulse';

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260824091823_fb38790d_09b6_4b62_a6de_53e7df831(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260824091823_fb38790d_09b6_4b62_a6de_53e7df831(boolean) TO authenticated, service_role;
