-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822031618_bd17cf76-e378-4299-846a-7a5d0751aa23.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822031618_bd17cf76_e378_4299_846a_7a5d0751a(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822031618_bd17cf76-e378-4299-846a-7a5d0751aa23.sql',
      'statements', 1
    );
  END IF;

  -- from 20260822031618_bd17cf76-e378-4299-846a-7a5d0751aa23.sql:2
  DELETE FROM public.user_preferences up
  WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = up.user_id);

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822031618_bd17cf76_e378_4299_846a_7a5d0751a(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822031618_bd17cf76_e378_4299_846a_7a5d0751a(boolean) TO authenticated, service_role;
