-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822040050_898aa1ae-fd04-419c-96f6-08b3a1434813.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822040050_898aa1ae_fd04_419c_96f6_08b3a1434(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822040050_898aa1ae-fd04-419c-96f6-08b3a1434813.sql',
      'statements', 2
    );
  END IF;

  -- from 20260822040050_898aa1ae-fd04-419c-96f6-08b3a1434813.sql:18
  INSERT INTO public.map_data_pulse (id, updated_at, point_count)
  VALUES (true, now(), 0)
  ON CONFLICT (id) DO NOTHING;

  -- from 20260822040050_898aa1ae-fd04-419c-96f6-08b3a1434813.sql:58
  INSERT INTO public.realtime_guard_allowlist (table_name, sensitivity, note, allow_replica_identity_full)
  VALUES ('map_data_pulse', 'public',
          'Aggregate heartbeat only: timestamp + cumulative count, no user or coordinate data.',
          false)
  ON CONFLICT (table_name) DO UPDATE
    SET sensitivity = EXCLUDED.sensitivity, note = EXCLUDED.note;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822040050_898aa1ae_fd04_419c_96f6_08b3a1434(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822040050_898aa1ae_fd04_419c_96f6_08b3a1434(boolean) TO authenticated, service_role;
