-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260819203856_5381c403-68f4-4b50-af40-da1c6a6b43cd.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260819203856_5381c403_68f4_4b50_af40_da1c6a6b4(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260819203856_5381c403-68f4-4b50-af40-da1c6a6b43cd.sql',
      'statements', 3
    );
  END IF;

  -- from 20260819203856_5381c403-68f4-4b50-af40-da1c6a6b43cd.sql:2
  DELETE FROM public.push_subscriptions a
  USING public.push_subscriptions b
  WHERE a.ctid < b.ctid
    AND a.endpoint = b.endpoint;

  -- from 20260819203856_5381c403-68f4-4b50-af40-da1c6a6b43cd.sql:70
  UPDATE public.profiles
  SET display_name = public.generate_auto_handle(id),
      display_name_claimed = false
  WHERE display_name IS NULL
     OR btrim(display_name) = ''
     OR display_name LIKE '%@%';

  -- from 20260819203856_5381c403-68f4-4b50-af40-da1c6a6b43cd.sql:78
  UPDATE public.profiles
  SET display_name_claimed = true
  WHERE display_name IS NOT NULL
    AND btrim(display_name) <> ''
    AND display_name NOT LIKE '%@%'
    AND display_name <> public.generate_auto_handle(id)
    AND display_name_claimed = false;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260819203856_5381c403_68f4_4b50_af40_da1c6a6b4(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260819203856_5381c403_68f4_4b50_af40_da1c6a6b4(boolean) TO authenticated, service_role;
