-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822045336_1b7b1d79-9c95-4090-90a8-aecc8708fa1b.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822045336_1b7b1d79_9c95_4090_90a8_aecc8708f(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822045336_1b7b1d79-9c95-4090-90a8-aecc8708fa1b.sql',
      'statements', 1
    );
  END IF;

  -- from 20260822045336_1b7b1d79-9c95-4090-90a8-aecc8708fa1b.sql:6
  DELETE FROM public.map_sync_latency_samples
  WHERE stage = 'end_to_end'
    AND latency_ms > 300000;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822045336_1b7b1d79_9c95_4090_90a8_aecc8708f(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822045336_1b7b1d79_9c95_4090_90a8_aecc8708f(boolean) TO authenticated, service_role;
