-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260828215948_62afbdc1-ad4b-44b6-a105-71386a6fa436.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260828215948_62afbdc1_ad4b_44b6_a105_71386a6fa(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260828215948_62afbdc1-ad4b-44b6-a105-71386a6fa436.sql',
      'statements', 1
    );
  END IF;

  -- from 20260828215948_62afbdc1-ad4b-44b6-a105-71386a6fa436.sql:3
  INSERT INTO public.social_handles (user_id, platform, handle, url)
  SELECT p.id, s.platform::public.social_platform,
         NULLIF(regexp_replace(regexp_replace(s.url, '^https?://[^/]+/', ''), '[/?].*$', ''), ''),
         s.url
  FROM public.profiles p
  CROSS JOIN LATERAL (
    VALUES ('instagram', p.instagram_url),
           ('twitter', p.twitter_url),
           ('facebook', p.facebook_url),
           ('linkedin', p.linkedin_url),
           ('tiktok', p.tiktok_url)
  ) AS s(platform, url)
  WHERE s.url IS NOT NULL AND s.url <> ''
    AND NULLIF(regexp_replace(regexp_replace(s.url, '^https?://[^/]+/', ''), '[/?].*$', ''), '') IS NOT NULL
  ON CONFLICT DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260828215948_62afbdc1_ad4b_44b6_a105_71386a6fa(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260828215948_62afbdc1_ad4b_44b6_a105_71386a6fa(boolean) TO authenticated, service_role;
