-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260824092149_0d5aacbf-5cb3-4e47-8b43-c13da39c43a9.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260824092149_0d5aacbf_5cb3_4e47_8b43_c13da39c4(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260824092149_0d5aacbf-5cb3-4e47-8b43-c13da39c43a9.sql',
      'statements', 1
    );
  END IF;

  -- from 20260824092149_0d5aacbf-5cb3-4e47-8b43-c13da39c43a9.sql:26
  INSERT INTO public.profile_pulse (profile_id, event, updated_at)
  SELECT p.id, 'updated', now() FROM public.profiles p
  ON CONFLICT (profile_id) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260824092149_0d5aacbf_5cb3_4e47_8b43_c13da39c4(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260824092149_0d5aacbf_5cb3_4e47_8b43_c13da39c4(boolean) TO authenticated, service_role;
