-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260816192452_84e327ba-9932-4272-b5c0-a6f7de1fe18e.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260816192452_84e327ba_9932_4272_b5c0_a6f7de1fe(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260816192452_84e327ba-9932-4272-b5c0-a6f7de1fe18e.sql',
      'statements', 2
    );
  END IF;

  -- from 20260816192452_84e327ba-9932-4272-b5c0-a6f7de1fe18e.sql:19
  UPDATE public.profiles
  SET display_name = public.generate_auto_handle(id),
      display_name_claimed = false
  WHERE display_name IS NULL
     OR btrim(display_name) = ''
     OR display_name LIKE '%@%';

  -- from 20260816192452_84e327ba-9932-4272-b5c0-a6f7de1fe18e.sql:26
  UPDATE public.profiles
  SET display_name_claimed = true
  WHERE display_name IS NOT NULL
    AND btrim(display_name) <> ''
    AND display_name NOT LIKE '%@%'
    AND display_name <> public.generate_auto_handle(id)
    AND display_name_claimed = false;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260816192452_84e327ba_9932_4272_b5c0_a6f7de1fe(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260816192452_84e327ba_9932_4272_b5c0_a6f7de1fe(boolean) TO authenticated, service_role;
