-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822045025_cc7e82a6-ed3a-4f50-af12-370392735cdc.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822045025_cc7e82a6_ed3a_4f50_af12_370392735(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822045025_cc7e82a6-ed3a-4f50-af12-370392735cdc.sql',
      'statements', 2
    );
  END IF;

  -- from 20260822045025_cc7e82a6-ed3a-4f50-af12-370392735cdc.sql:18
  DELETE FROM public.realtime_guard_allowlist WHERE table_name = 'deal_shares';

  -- from 20260822045025_cc7e82a6-ed3a-4f50-af12-370392735cdc.sql:21
  UPDATE public.realtime_guard_alerts
     SET status = 'resolved', resolved_at = now(), updated_at = now()
   WHERE status = 'open' AND target = 'deal_shares';

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822045025_cc7e82a6_ed3a_4f50_af12_370392735(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822045025_cc7e82a6_ed3a_4f50_af12_370392735(boolean) TO authenticated, service_role;
