-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822045932_ba3f3369-1abf-4059-82b1-a801efd9f29e.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822045932_ba3f3369_1abf_4059_82b1_a801efd9f(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822045932_ba3f3369-1abf-4059-82b1-a801efd9f29e.sql',
      'statements', 1
    );
  END IF;

  -- from 20260822045932_ba3f3369-1abf-4059-82b1-a801efd9f29e.sql:2
  DELETE FROM public.map_sync_latency_samples
  WHERE stage = 'end_to_end' AND latency_ms > 45000;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822045932_ba3f3369_1abf_4059_82b1_a801efd9f(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822045932_ba3f3369_1abf_4059_82b1_a801efd9f(boolean) TO authenticated, service_role;
