-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822032018_cc9b1cba-c67d-4f0e-9882-142d47551320.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822032018_cc9b1cba_c67d_4f0e_9882_142d47551(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822032018_cc9b1cba-c67d-4f0e-9882-142d47551320.sql',
      'statements', 1
    );
  END IF;

  -- from 20260822032018_cc9b1cba-c67d-4f0e-9882-142d47551320.sql:47
  INSERT INTO public.map_sync_latency_thresholds (stage, warn_ms, crit_ms, min_samples) VALUES
    ('write', 1500, 4000, 5),
    ('fetch', 2500, 6000, 5),
    ('render', 1200, 3000, 5),
    ('end_to_end', 45000, 90000, 5)
  ON CONFLICT (stage) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822032018_cc9b1cba_c67d_4f0e_9882_142d47551(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822032018_cc9b1cba_c67d_4f0e_9882_142d47551(boolean) TO authenticated, service_role;
