-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260824080519_3e63d36e-1fd9-41a6-ab36-f40f0b350980.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260824080519_3e63d36e_1fd9_41a6_ab36_f40f0b350(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260824080519_3e63d36e-1fd9-41a6-ab36-f40f0b350980.sql',
      'statements', 1
    );
  END IF;

  -- from 20260824080519_3e63d36e-1fd9-41a6-ab36-f40f0b350980.sql:37
  INSERT INTO public.realtime_guard_allowlist (table_name, sensitivity, note, allow_replica_identity_full)
  VALUES ('profile_pulse', 'public', 'Heartbeat only: profile id + created/updated flag + timestamp. No profile content.', false)
  ON CONFLICT (table_name) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260824080519_3e63d36e_1fd9_41a6_ab36_f40f0b350(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260824080519_3e63d36e_1fd9_41a6_ab36_f40f0b350(boolean) TO authenticated, service_role;
