-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260824091250_64b53a7c-959d-4603-8e7a-47cc36e496a1.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260824091250_64b53a7c_959d_4603_8e7a_47cc36e49(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260824091250_64b53a7c-959d-4603-8e7a-47cc36e496a1.sql',
      'statements', 1
    );
  END IF;

  -- from 20260824091250_64b53a7c-959d-4603-8e7a-47cc36e496a1.sql:52
  INSERT INTO public.social_handles (user_id, platform, handle, url)
  SELECT
    p.id,
    platform.platform::public.social_platform,
    CASE platform.platform
      WHEN 'instagram' THEN NULLIF(regexp_replace(p.instagram_url, '^https?://(www\.)?instagram\.com/([^/?#]+).*$', '\2'), p.instagram_url)
      WHEN 'twitter' THEN NULLIF(regexp_replace(p.twitter_url, '^https?://(www\.)?(twitter|x)\.com/([^/?#]+).*$', '\3'), p.twitter_url)
      WHEN 'facebook' THEN NULLIF(regexp_replace(p.facebook_url, '^https?://(www\.)?facebook\.com/([^/?#]+).*$', '\2'), p.facebook_url)
      WHEN 'linkedin' THEN NULLIF(regexp_replace(p.linkedin_url, '^https?://(www\.)?linkedin\.com/in/([^/?#]+).*$', '\2'), p.linkedin_url)
      WHEN 'tiktok' THEN NULLIF(regexp_replace(p.tiktok_url, '^https?://(www\.)?tiktok\.com/@([^/?#]+).*$', '\2'), p.tiktok_url)
    END,
    CASE platform.platform
      WHEN 'instagram' THEN p.instagram_url
      WHEN 'twitter' THEN p.twitter_url
      WHEN 'facebook' THEN p.facebook_url
      WHEN 'linkedin' THEN p.linkedin_url
      WHEN 'tiktok' THEN p.tiktok_url
    END
  FROM public.profiles p
  CROSS JOIN (
    VALUES
      ('instagram'::public.social_platform),
      ('twitter'::public.social_platform),
      ('facebook'::public.social_platform),
      ('linkedin'::public.social_platform),
      ('tiktok'::public.social_platform)
  ) AS platform(platform)
  WHERE
    CASE platform.platform
      WHEN 'instagram' THEN p.instagram_url IS NOT NULL AND p.instagram_url <> ''
      WHEN 'twitter' THEN p.twitter_url IS NOT NULL AND p.twitter_url <> ''
      WHEN 'facebook' THEN p.facebook_url IS NOT NULL AND p.facebook_url <> ''
      WHEN 'linkedin' THEN p.linkedin_url IS NOT NULL AND p.linkedin_url <> ''
      WHEN 'tiktok' THEN p.tiktok_url IS NOT NULL AND p.tiktok_url <> ''
    END
  ON CONFLICT (user_id, platform) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260824091250_64b53a7c_959d_4603_8e7a_47cc36e49(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260824091250_64b53a7c_959d_4603_8e7a_47cc36e49(boolean) TO authenticated, service_role;
