-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260823013025_ba8ada78-4f65-4060-8bae-becd79e90f3e.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260823013025_ba8ada78_4f65_4060_8bae_becd79e90(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260823013025_ba8ada78-4f65-4060-8bae-becd79e90f3e.sql',
      'statements', 1
    );
  END IF;

  -- from 20260823013025_ba8ada78-4f65-4060-8bae-becd79e90f3e.sql:16
  INSERT INTO public.realtime_guard_allowlist
    (table_name, sensitivity, note, allow_replica_identity_full)
  VALUES
    ('subscribers', 'private', 'Paywall state. RLS is SELECT-own; replica identity DEFAULT so no billing PII in old payloads.', false)
  ON CONFLICT (table_name) DO UPDATE
    SET sensitivity = EXCLUDED.sensitivity,
        note = EXCLUDED.note,
        allow_replica_identity_full = EXCLUDED.allow_replica_identity_full;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260823013025_ba8ada78_4f65_4060_8bae_becd79e90(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260823013025_ba8ada78_4f65_4060_8bae_becd79e90(boolean) TO authenticated, service_role;
