-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260824082317_01db8f88-025d-4992-baaa-63f88798a419.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260824082317_01db8f88_025d_4992_baaa_63f88798a(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260824082317_01db8f88-025d-4992-baaa-63f88798a419.sql',
      'statements', 1
    );
  END IF;

  -- from 20260824082317_01db8f88-025d-4992-baaa-63f88798a419.sql:30
  UPDATE public.realtime_guard_allowlist
  SET sensitivity = 'private',
      note = 'Heartbeat only (profile id + created/updated flag + timestamp). Reads scoped to self, accepted connections and discoverable profiles.'
  WHERE table_name = 'profile_pulse';

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260824082317_01db8f88_025d_4992_baaa_63f88798a(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260824082317_01db8f88_025d_4992_baaa_63f88798a(boolean) TO authenticated, service_role;
