-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260813051512_5833e8d0-ee67-4889-a679-d1f17af58cdf.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260813051512_5833e8d0_ee67_4889_a679_d1f17af58(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260813051512_5833e8d0-ee67-4889-a679-d1f17af58cdf.sql',
      'statements', 1
    );
  END IF;

  -- from 20260813051512_5833e8d0-ee67-4889-a679-d1f17af58cdf.sql:88
  DELETE FROM public.push_subscriptions older
  USING public.push_subscriptions newer
  WHERE older.endpoint = newer.endpoint
    AND (
      older.updated_at < newer.updated_at
      OR (older.updated_at IS NOT DISTINCT FROM newer.updated_at AND older.ctid < newer.ctid)
    );

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260813051512_5833e8d0_ee67_4889_a679_d1f17af58(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260813051512_5833e8d0_ee67_4889_a679_d1f17af58(boolean) TO authenticated, service_role;
