-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260822041853_c258d2da-2a4f-419e-a459-dd5f417cbab4.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260822041853_c258d2da_2a4f_419e_a459_dd5f417cb(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260822041853_c258d2da-2a4f-419e-a459-dd5f417cbab4.sql',
      'statements', 1
    );
  END IF;

  -- from 20260822041853_c258d2da-2a4f-419e-a459-dd5f417cbab4.sql:24
  INSERT INTO public.realtime_guard_allowlist (table_name, sensitivity, note, allow_replica_identity_full)
  VALUES (
    'deal_shares',
    'private',
    'Owner + admins only; REPLICA IDENTITY DEFAULT so delete payloads carry the primary key only.',
    false
  )
  ON CONFLICT (table_name) DO UPDATE
    SET sensitivity = EXCLUDED.sensitivity,
        note = EXCLUDED.note,
        allow_replica_identity_full = EXCLUDED.allow_replica_identity_full;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260822041853_c258d2da_2a4f_419e_a459_dd5f417cb(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260822041853_c258d2da_2a4f_419e_a459_dd5f417cb(boolean) TO authenticated, service_role;
