-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260820120113_6d9616af-c952-4c1d-8439-f42884a5c960.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260820120113_6d9616af_c952_4c1d_8439_f42884a5c(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260820120113_6d9616af-c952-4c1d-8439-f42884a5c960.sql',
      'statements', 1
    );
  END IF;

  -- from 20260820120113_6d9616af-c952-4c1d-8439-f42884a5c960.sql:23
  INSERT INTO public.realtime_guard_allowlist (table_name, sensitivity, note) VALUES
    ('deals',            'public',  'Merchant deals; public SELECT policy is intended'),
    ('user_connections', 'private', 'Requester + recipient only, at any status'),
    ('user_favorites',   'private', 'Owner only'),
    ('search_history',   'private', 'Owner only'),
    ('venue_reviews',    'private', 'Author, admins and accepted connections')
  ON CONFLICT (table_name) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260820120113_6d9616af_c952_4c1d_8439_f42884a5c(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260820120113_6d9616af_c952_4c1d_8439_f42884a5c(boolean) TO authenticated, service_role;
