-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260802132658_54bf873e-49f0-4fab-a847-9caabeec71e9.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260802132658_54bf873e_49f0_4fab_a847_9caabeec7(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260802132658_54bf873e-49f0-4fab-a847-9caabeec71e9.sql',
      'statements', 1
    );
  END IF;

  -- from 20260802132658_54bf873e-49f0-4fab-a847-9caabeec71e9.sql:2
  UPDATE public.profiles SET discoverable = true WHERE discoverable IS NULL;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260802132658_54bf873e_49f0_4fab_a847_9caabeec7(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260802132658_54bf873e_49f0_4fab_a847_9caabeec7(boolean) TO authenticated, service_role;
