-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260731192118_b231d6fa-3c6a-4e14-9237-a2aec4a79be4.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260731192118_b231d6fa_3c6a_4e14_9237_a2aec4a79(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260731192118_b231d6fa-3c6a-4e14-9237-a2aec4a79be4.sql',
      'statements', 3
    );
  END IF;

  -- from 20260731192118_b231d6fa-3c6a-4e14-9237-a2aec4a79be4.sql:2
  INSERT INTO public.profiles (id, display_name)
  SELECT u.id, COALESCE(u.raw_user_meta_data->>'display_name', u.email)
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.id = u.id
  WHERE p.id IS NULL
  ON CONFLICT (id) DO NOTHING;

  -- from 20260731192118_b231d6fa-3c6a-4e14-9237-a2aec4a79be4.sql:9
  INSERT INTO public.user_preferences (user_id)
  SELECT u.id
  FROM auth.users u
  LEFT JOIN public.user_preferences up ON up.user_id = u.id
  WHERE up.user_id IS NULL
  ON CONFLICT (user_id) DO NOTHING;

  -- from 20260731192118_b231d6fa-3c6a-4e14-9237-a2aec4a79be4.sql:16
  UPDATE public.profiles p
  SET display_name = COALESCE(u.raw_user_meta_data->>'display_name', u.email),
      updated_at = now()
  FROM auth.users u
  WHERE u.id = p.id
    AND (p.display_name IS NULL OR btrim(p.display_name) = '');

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260731192118_b231d6fa_3c6a_4e14_9237_a2aec4a79(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260731192118_b231d6fa_3c6a_4e14_9237_a2aec4a79(boolean) TO authenticated, service_role;
