-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260810234047_ccd77168-d365-4713-8417-0329beff15b9.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260810234047_ccd77168_d365_4713_8417_0329beff1(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260810234047_ccd77168-d365-4713-8417-0329beff15b9.sql',
      'statements', 1
    );
  END IF;

  -- from 20260810234047_ccd77168-d365-4713-8417-0329beff15b9.sql:15
  DELETE FROM public.push_subscriptions a
  USING public.push_subscriptions b
  WHERE a.ctid < b.ctid
    AND a.user_id IS NOT DISTINCT FROM b.user_id
    AND a.endpoint = b.endpoint;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260810234047_ccd77168_d365_4713_8417_0329beff1(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260810234047_ccd77168_d365_4713_8417_0329beff1(boolean) TO authenticated, service_role;
