-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260811034744_3ed0156e-ad28-4787-8c62-f81a021bbc95.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260811034744_3ed0156e_ad28_4787_8c62_f81a021bb(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260811034744_3ed0156e-ad28-4787-8c62-f81a021bbc95.sql',
      'statements', 1
    );
  END IF;

  -- from 20260811034744_3ed0156e-ad28-4787-8c62-f81a021bbc95.sql:15
  DELETE FROM public.push_subscriptions a
  USING public.push_subscriptions b
  WHERE a.ctid < b.ctid
    AND a.endpoint = b.endpoint;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260811034744_3ed0156e_ad28_4787_8c62_f81a021bb(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260811034744_3ed0156e_ad28_4787_8c62_f81a021bb(boolean) TO authenticated, service_role;
