-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260823023112_b9db0695-b50e-4772-bb9d-fb457e3cc55c.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260823023112_b9db0695_b50e_4772_bb9d_fb457e3cc(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260823023112_b9db0695-b50e-4772-bb9d-fb457e3cc55c.sql',
      'statements', 2
    );
  END IF;

  -- from 20260823023112_b9db0695-b50e-4772-bb9d-fb457e3cc55c.sql:65
  INSERT INTO public.realtime_guard_allowlist
    (table_name, sensitivity, note, allow_replica_identity_full)
  VALUES
    ('app_config', 'public', 'Global feature flags (e.g. monetization_enabled). No user data; readable by everyone by design.', false)
  ON CONFLICT (table_name) DO UPDATE
    SET sensitivity = EXCLUDED.sensitivity,
        note = EXCLUDED.note,
        allow_replica_identity_full = EXCLUDED.allow_replica_identity_full;

  -- from 20260823023112_b9db0695-b50e-4772-bb9d-fb457e3cc55c.sql:75
  INSERT INTO public.app_config (key, value)
  VALUES ('monetization_enabled', 'false'::jsonb)
  ON CONFLICT (key) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260823023112_b9db0695_b50e_4772_bb9d_fb457e3cc(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260823023112_b9db0695_b50e_4772_bb9d_fb457e3cc(boolean) TO authenticated, service_role;
