-- GENERATED by scripts/extract-migration-dml.mjs — do not edit by hand.
-- One-off admin backfill extracted from 20260726214731_8ce9bc93-6214-45ff-a663-a9c720f98924.sql.
-- Run it from the admin dashboard (or as service_role) instead of shipping
-- the DML inside a migration.

CREATE OR REPLACE FUNCTION public.admin_backfill_20260726214731_8ce9bc93_6214_45ff_a663_a9c720f98(_dry_run boolean DEFAULT true)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  _affected bigint := 0;
  _rows bigint;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'admin role required';
  END IF;

  IF _dry_run THEN
    RETURN jsonb_build_object(
      'dry_run', true,
      'source_migration', '20260726214731_8ce9bc93-6214-45ff-a663-a9c720f98924.sql',
      'statements', 1
    );
  END IF;

  -- from 20260726214731_8ce9bc93-6214-45ff-a663-a9c720f98924.sql:25
  INSERT INTO public.user_preferences (user_id)
  SELECT p.id FROM public.profiles p
  LEFT JOIN public.user_preferences up ON up.user_id = p.id
  WHERE up.user_id IS NULL
  ON CONFLICT (user_id) DO NOTHING;

  GET DIAGNOSTICS _rows = ROW_COUNT;
  _affected := _affected + _rows;

  RETURN jsonb_build_object('dry_run', false, 'rows_affected', _affected);
END;
$fn$;

REVOKE EXECUTE ON FUNCTION public.admin_backfill_20260726214731_8ce9bc93_6214_45ff_a663_a9c720f98(boolean) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_backfill_20260726214731_8ce9bc93_6214_45ff_a663_a9c720f98(boolean) TO authenticated, service_role;
