/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SocialRouteImport } from './routes/social'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as VerificationSuccessRouteImport } from './routes/verification-success'
import { Route as GuidesCharlotteHappyHourRouteImport } from './routes/guides/charlotte-happy-hour'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable/oauth/consent'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicHooksNudgeIncompleteOnboardingRouteImport } from './routes/api/public/hooks/nudge-incomplete-onboarding'
import { Route as ApiPublicHooksResendMarketingEventsRouteImport } from './routes/api/public/hooks/resend-marketing-events'
import { Route as ApiPublicHooksSyncResendAudienceRouteImport } from './routes/api/public/hooks/sync-resend-audience'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationSuccessRoute = VerificationSuccessRouteImport.update({
  id: '/verification-success',
  path: '/verification-success',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCharlotteHappyHourRoute =
  GuidesCharlotteHappyHourRouteImport.update({
    id: '/guides/charlotte-happy-hour',
    path: '/guides/charlotte-happy-hour',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNudgeIncompleteOnboardingRoute =
  ApiPublicHooksNudgeIncompleteOnboardingRouteImport.update({
    id: '/api/public/hooks/nudge-incomplete-onboarding',
    path: '/api/public/hooks/nudge-incomplete-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResendMarketingEventsRoute =
  ApiPublicHooksResendMarketingEventsRouteImport.update({
    id: '/api/public/hooks/resend-marketing-events',
    path: '/api/public/hooks/resend-marketing-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncResendAudienceRoute =
  ApiPublicHooksSyncResendAudienceRouteImport.update({
    id: '/api/public/hooks/sync-resend-audience',
    path: '/api/public/hooks/sync-resend-audience',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verification-success': typeof VerificationSuccessRoute
  '/guides/charlotte-happy-hour': typeof GuidesCharlotteHappyHourRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/hooks/nudge-incomplete-onboarding': typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  '/api/public/hooks/resend-marketing-events': typeof ApiPublicHooksResendMarketingEventsRoute
  '/api/public/hooks/sync-resend-audience': typeof ApiPublicHooksSyncResendAudienceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verification-success': typeof VerificationSuccessRoute
  '/guides/charlotte-happy-hour': typeof GuidesCharlotteHappyHourRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/hooks/nudge-incomplete-onboarding': typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  '/api/public/hooks/resend-marketing-events': typeof ApiPublicHooksResendMarketingEventsRoute
  '/api/public/hooks/sync-resend-audience': typeof ApiPublicHooksSyncResendAudienceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/verification-success': typeof VerificationSuccessRoute
  '/guides/charlotte-happy-hour': typeof GuidesCharlotteHappyHourRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/hooks/nudge-incomplete-onboarding': typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  '/api/public/hooks/resend-marketing-events': typeof ApiPublicHooksResendMarketingEventsRoute
  '/api/public/hooks/sync-resend-audience': typeof ApiPublicHooksSyncResendAudienceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/messages'
    | '/onboarding'
    | '/privacy-policy'
    | '/profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/social'
    | '/terms-of-service'
    | '/verification-success'
    | '/guides/charlotte-happy-hour'
    | '/.lovable/oauth/consent'
    | '/api/public/version'
    | '/api/public/hooks/nudge-incomplete-onboarding'
    | '/api/public/hooks/resend-marketing-events'
    | '/api/public/hooks/sync-resend-audience'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/messages'
    | '/onboarding'
    | '/privacy-policy'
    | '/profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/social'
    | '/terms-of-service'
    | '/verification-success'
    | '/guides/charlotte-happy-hour'
    | '/.lovable/oauth/consent'
    | '/api/public/version'
    | '/api/public/hooks/nudge-incomplete-onboarding'
    | '/api/public/hooks/resend-marketing-events'
    | '/api/public/hooks/sync-resend-audience'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/messages'
    | '/onboarding'
    | '/privacy-policy'
    | '/profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/social'
    | '/terms-of-service'
    | '/verification-success'
    | '/guides/charlotte-happy-hour'
    | '/.lovable/oauth/consent'
    | '/api/public/version'
    | '/api/public/hooks/nudge-incomplete-onboarding'
    | '/api/public/hooks/resend-marketing-events'
    | '/api/public/hooks/sync-resend-audience'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  VerificationSuccessRoute: typeof VerificationSuccessRoute
  GuidesCharlotteHappyHourRoute: typeof GuidesCharlotteHappyHourRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicHooksNudgeIncompleteOnboardingRoute: typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  ApiPublicHooksResendMarketingEventsRoute: typeof ApiPublicHooksResendMarketingEventsRoute
  ApiPublicHooksSyncResendAudienceRoute: typeof ApiPublicHooksSyncResendAudienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-success': {
      id: '/verification-success'
      path: '/verification-success'
      fullPath: '/verification-success'
      preLoaderRoute: typeof VerificationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/charlotte-happy-hour': {
      id: '/guides/charlotte-happy-hour'
      path: '/guides/charlotte-happy-hour'
      fullPath: '/guides/charlotte-happy-hour'
      preLoaderRoute: typeof GuidesCharlotteHappyHourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nudge-incomplete-onboarding': {
      id: '/api/public/hooks/nudge-incomplete-onboarding'
      path: '/api/public/hooks/nudge-incomplete-onboarding'
      fullPath: '/api/public/hooks/nudge-incomplete-onboarding'
      preLoaderRoute: typeof ApiPublicHooksNudgeIncompleteOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resend-marketing-events': {
      id: '/api/public/hooks/resend-marketing-events'
      path: '/api/public/hooks/resend-marketing-events'
      fullPath: '/api/public/hooks/resend-marketing-events'
      preLoaderRoute: typeof ApiPublicHooksResendMarketingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-resend-audience': {
      id: '/api/public/hooks/sync-resend-audience'
      path: '/api/public/hooks/sync-resend-audience'
      fullPath: '/api/public/hooks/sync-resend-audience'
      preLoaderRoute: typeof ApiPublicHooksSyncResendAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  VerificationSuccessRoute: VerificationSuccessRoute,
  GuidesCharlotteHappyHourRoute: GuidesCharlotteHappyHourRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicHooksNudgeIncompleteOnboardingRoute:
    ApiPublicHooksNudgeIncompleteOnboardingRoute,
  ApiPublicHooksResendMarketingEventsRoute:
    ApiPublicHooksResendMarketingEventsRoute,
  ApiPublicHooksSyncResendAudienceRoute: ApiPublicHooksSyncResendAudienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
