/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as EmailConfirmedRouteImport } from './routes/email-confirmed'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SocialRouteImport } from './routes/social'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as VerificationSuccessRouteImport } from './routes/verification-success'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as DevPresenceRouteImport } from './routes/dev/presence'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable/oauth/consent'
import { Route as ApiPublicDeviceTokensRouteImport } from './routes/api/public/device-tokens'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicHooksNudgeIncompleteOnboardingRouteImport } from './routes/api/public/hooks/nudge-incomplete-onboarding'
import { Route as ApiPublicHooksResendMarketingEventsRouteImport } from './routes/api/public/hooks/resend-marketing-events'
import { Route as ApiPublicHooksSyncResendAudienceRouteImport } from './routes/api/public/hooks/sync-resend-audience'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmedRoute = EmailConfirmedRouteImport.update({
  id: '/email-confirmed',
  path: '/email-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationSuccessRoute = VerificationSuccessRouteImport.update({
  id: '/verification-success',
  path: '/verification-success',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPresenceRoute = DevPresenceRouteImport.update({
  id: '/dev/presence',
  path: '/dev/presence',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceTokensRoute = ApiPublicDeviceTokensRouteImport.update({
  id: '/api/public/device-tokens',
  path: '/api/public/device-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNudgeIncompleteOnboardingRoute =
  ApiPublicHooksNudgeIncompleteOnboardingRouteImport.update({
    id: '/api/public/hooks/nudge-incomplete-onboarding',
    path: '/api/public/hooks/nudge-incomplete-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResendMarketingEventsRoute =
  ApiPublicHooksResendMarketingEventsRouteImport.update({
    id: '/api/public/hooks/resend-marketing-events',
    path: '/api/public/hooks/resend-marketing-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncResendAudienceRoute =
  ApiPublicHooksSyncResendAudienceRouteImport.update({
    id: '/api/public/hooks/sync-resend-audience',
    path: '/api/public/hooks/sync-resend-audience',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/confirm': typeof ConfirmRoute
  '/deals': typeof DealsRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/update-password': typeof UpdatePasswordRoute
  '/verification-success': typeof VerificationSuccessRoute
  '/verify': typeof VerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dev/presence': typeof DevPresenceRoute
  '/auth/': typeof AuthIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/device-tokens': typeof ApiPublicDeviceTokensRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/hooks/nudge-incomplete-onboarding': typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  '/api/public/hooks/resend-marketing-events': typeof ApiPublicHooksResendMarketingEventsRoute
  '/api/public/hooks/sync-resend-audience': typeof ApiPublicHooksSyncResendAudienceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/confirm': typeof ConfirmRoute
  '/deals': typeof DealsRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/update-password': typeof UpdatePasswordRoute
  '/verification-success': typeof VerificationSuccessRoute
  '/verify': typeof VerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dev/presence': typeof DevPresenceRoute
  '/auth': typeof AuthIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/device-tokens': typeof ApiPublicDeviceTokensRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/hooks/nudge-incomplete-onboarding': typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  '/api/public/hooks/resend-marketing-events': typeof ApiPublicHooksResendMarketingEventsRoute
  '/api/public/hooks/sync-resend-audience': typeof ApiPublicHooksSyncResendAudienceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/confirm': typeof ConfirmRoute
  '/deals': typeof DealsRoute
  '/email-confirmed': typeof EmailConfirmedRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/update-password': typeof UpdatePasswordRoute
  '/verification-success': typeof VerificationSuccessRoute
  '/verify': typeof VerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dev/presence': typeof DevPresenceRoute
  '/auth/': typeof AuthIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/device-tokens': typeof ApiPublicDeviceTokensRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/hooks/nudge-incomplete-onboarding': typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  '/api/public/hooks/resend-marketing-events': typeof ApiPublicHooksResendMarketingEventsRoute
  '/api/public/hooks/sync-resend-audience': typeof ApiPublicHooksSyncResendAudienceRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/confirm'
    | '/deals'
    | '/email-confirmed'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/redeem'
    | '/register'
    | '/reset'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/signin'
    | '/signup'
    | '/social'
    | '/terms-of-service'
    | '/update-password'
    | '/verification-success'
    | '/verify'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/reset'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dev/presence'
    | '/auth/'
    | '/.lovable/oauth/consent'
    | '/api/public/device-tokens'
    | '/api/public/version'
    | '/api/public/hooks/nudge-incomplete-onboarding'
    | '/api/public/hooks/resend-marketing-events'
    | '/api/public/hooks/sync-resend-audience'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/confirm'
    | '/deals'
    | '/email-confirmed'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/redeem'
    | '/register'
    | '/reset'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/signin'
    | '/signup'
    | '/social'
    | '/terms-of-service'
    | '/update-password'
    | '/verification-success'
    | '/verify'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/reset'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dev/presence'
    | '/auth'
    | '/.lovable/oauth/consent'
    | '/api/public/device-tokens'
    | '/api/public/version'
    | '/api/public/hooks/nudge-incomplete-onboarding'
    | '/api/public/hooks/resend-marketing-events'
    | '/api/public/hooks/sync-resend-audience'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/confirm'
    | '/deals'
    | '/email-confirmed'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/redeem'
    | '/register'
    | '/reset'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/signin'
    | '/signup'
    | '/social'
    | '/terms-of-service'
    | '/update-password'
    | '/verification-success'
    | '/verify'
    | '/auth/callback'
    | '/auth/confirm'
    | '/auth/reset'
    | '/auth/reset-password'
    | '/auth/verify'
    | '/dev/presence'
    | '/auth/'
    | '/.lovable/oauth/consent'
    | '/api/public/device-tokens'
    | '/api/public/version'
    | '/api/public/hooks/nudge-incomplete-onboarding'
    | '/api/public/hooks/resend-marketing-events'
    | '/api/public/hooks/sync-resend-audience'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  ConfirmRoute: typeof ConfirmRoute
  DealsRoute: typeof DealsRoute
  EmailConfirmedRoute: typeof EmailConfirmedRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RedeemRoute: typeof RedeemRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  VerificationSuccessRoute: typeof VerificationSuccessRoute
  VerifyRoute: typeof VerifyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  DevPresenceRoute: typeof DevPresenceRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicDeviceTokensRoute: typeof ApiPublicDeviceTokensRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicHooksNudgeIncompleteOnboardingRoute: typeof ApiPublicHooksNudgeIncompleteOnboardingRoute
  ApiPublicHooksResendMarketingEventsRoute: typeof ApiPublicHooksResendMarketingEventsRoute
  ApiPublicHooksSyncResendAudienceRoute: typeof ApiPublicHooksSyncResendAudienceRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-confirmed': {
      id: '/email-confirmed'
      path: '/email-confirmed'
      fullPath: '/email-confirmed'
      preLoaderRoute: typeof EmailConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-success': {
      id: '/verification-success'
      path: '/verification-success'
      fullPath: '/verification-success'
      preLoaderRoute: typeof VerificationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/presence': {
      id: '/dev/presence'
      path: '/dev/presence'
      fullPath: '/dev/presence'
      preLoaderRoute: typeof DevPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device-tokens': {
      id: '/api/public/device-tokens'
      path: '/api/public/device-tokens'
      fullPath: '/api/public/device-tokens'
      preLoaderRoute: typeof ApiPublicDeviceTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nudge-incomplete-onboarding': {
      id: '/api/public/hooks/nudge-incomplete-onboarding'
      path: '/api/public/hooks/nudge-incomplete-onboarding'
      fullPath: '/api/public/hooks/nudge-incomplete-onboarding'
      preLoaderRoute: typeof ApiPublicHooksNudgeIncompleteOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resend-marketing-events': {
      id: '/api/public/hooks/resend-marketing-events'
      path: '/api/public/hooks/resend-marketing-events'
      fullPath: '/api/public/hooks/resend-marketing-events'
      preLoaderRoute: typeof ApiPublicHooksResendMarketingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-resend-audience': {
      id: '/api/public/hooks/sync-resend-audience'
      path: '/api/public/hooks/sync-resend-audience'
      fullPath: '/api/public/hooks/sync-resend-audience'
      preLoaderRoute: typeof ApiPublicHooksSyncResendAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  ConfirmRoute: ConfirmRoute,
  DealsRoute: DealsRoute,
  EmailConfirmedRoute: EmailConfirmedRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RedeemRoute: RedeemRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  VerificationSuccessRoute: VerificationSuccessRoute,
  VerifyRoute: VerifyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthResetRoute: AuthResetRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  DevPresenceRoute: DevPresenceRoute,
  AuthIndexRoute: AuthIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicDeviceTokensRoute: ApiPublicDeviceTokensRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicHooksNudgeIncompleteOnboardingRoute:
    ApiPublicHooksNudgeIncompleteOnboardingRoute,
  ApiPublicHooksResendMarketingEventsRoute:
    ApiPublicHooksResendMarketingEventsRoute,
  ApiPublicHooksSyncResendAudienceRoute: ApiPublicHooksSyncResendAudienceRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
