// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-deals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-deals.ts
var list_deals_default = defineTool({
  name: "list_deals",
  title: "List active deals",
  description: "List currently active JET-Around deals in Charlotte, NC, optionally filtered by a text search over the title, description, or venue name.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional text to match against deal title, description, or venue name."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of deals to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    let query = supabase.from("deals").select("id, title, description, deal_type, venue_name, venue_address, starts_at, expires_at, website_url").eq("active", true).lte("starts_at", nowIso).gte("expires_at", nowIso).order("expires_at", { ascending: true }).limit(limit ?? 20);
    if (search) {
      const term = search.replace(/[%,]/g, " ").trim();
      query = query.or(
        `title.ilike.%${term}%,description.ilike.%${term}%,venue_name.ilike.%${term}%`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { deals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_favorites_default = defineTool2({
  name: "list_favorites",
  title: "List my saved venues",
  description: "List the venues and deals the signed-in user has saved to their JET-Around favorites.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum number of favorites to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_favorites").select("id, venue_id, venue_name, venue_address, venue_category, venue_neighborhood, deal_id, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-favorite.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var save_favorite_default = defineTool3({
  name: "save_favorite",
  title: "Save a venue to favorites",
  description: "Save a venue (and optionally a specific deal) to the signed-in user's JET-Around favorites.",
  inputSchema: {
    venue_id: z3.string().trim().describe("Identifier of the venue to save."),
    venue_name: z3.string().trim().describe("Display name of the venue."),
    venue_address: z3.string().trim().optional().describe("Street address of the venue."),
    venue_category: z3.string().trim().optional().describe("Category such as food, drink, nightlife, or events."),
    deal_id: z3.string().uuid().optional().describe("Optional deal id to associate with this favorite.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_favorites").insert({ ...input, user_id: ctx.getUserId() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved ${input.venue_name} to favorites.` }],
      structuredContent: { favorite: data }
    };
  }
});

// src/lib/mcp/tools/remove-favorite.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var remove_favorite_default = defineTool4({
  name: "remove_favorite",
  title: "Remove a saved venue",
  description: "Remove a saved venue from the signed-in user's JET-Around favorites by favorite id or venue id.",
  inputSchema: {
    favorite_id: z4.string().uuid().optional().describe("Id of the favorite row to remove."),
    venue_id: z4.string().trim().optional().describe("Venue id to remove from favorites when the favorite id is unknown.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ favorite_id, venue_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!favorite_id && !venue_id) {
      return { content: [{ type: "text", text: "Provide favorite_id or venue_id." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("user_favorites").delete().eq("user_id", ctx.getUserId());
    query = favorite_id ? query.eq("id", favorite_id) : query.eq("venue_id", venue_id);
    const { data, error } = await query.select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Removed ${data?.length ?? 0} favorite(s).` }],
      structuredContent: { removed: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/heatmap-density.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
function distanceKm(lat1, lng1, lat2, lng2) {
  const R = 6371;
  const toRad = (d) => d * Math.PI / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}
var heatmap_density_default = defineTool5({
  name: "get_heatmap_density",
  title: "Get heatmap density snapshot",
  description: "Return the latest aggregated, anonymized crowd-density snapshot (grid cells with activity counts) for a time range, optionally limited to a radius around a location in Charlotte, NC.",
  inputSchema: {
    time_window_minutes: z5.number().int().min(1).max(10080).optional().describe("How far back to look, in minutes (1 to 10080). Default 60."),
    latitude: z5.number().min(-90).max(90).optional().describe("Center latitude to filter around."),
    longitude: z5.number().min(-180).max(180).optional().describe("Center longitude to filter around."),
    radius_km: z5.number().min(0.1).max(100).optional().describe("Radius in kilometers around the center point (default 5, requires latitude/longitude)."),
    limit: z5.number().int().min(1).max(200).optional().describe("Maximum number of density cells to return, busiest first (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ time_window_minutes, latitude, longitude, radius_km, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (latitude === void 0 !== (longitude === void 0)) {
      return {
        content: [{ type: "text", text: "Provide both latitude and longitude, or neither." }],
        isError: true
      };
    }
    const windowMinutes = time_window_minutes ?? 60;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.functions.invoke("get-location-density", {
      body: { time_window_minutes: windowMinutes }
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const features = data?.geojson?.features ?? [];
    const radius = radius_km ?? 5;
    let cells = features.map((f) => {
      const [lng, lat] = f.geometry?.coordinates ?? [NaN, NaN];
      return {
        latitude: lat,
        longitude: lng,
        density: f.properties?.density ?? 0,
        intensity: f.properties?.intensity ?? 0
      };
    }).filter((c) => Number.isFinite(c.latitude) && Number.isFinite(c.longitude));
    if (latitude !== void 0 && longitude !== void 0) {
      cells = cells.map((c) => ({
        ...c,
        distance_km: Number(distanceKm(latitude, longitude, c.latitude, c.longitude).toFixed(3))
      })).filter((c) => c.distance_km <= radius);
    }
    cells.sort((a, b) => b.density - a.density);
    cells = cells.slice(0, limit ?? 50);
    const snapshot = {
      generated_at: (/* @__PURE__ */ new Date()).toISOString(),
      time_window_minutes: windowMinutes,
      center: latitude !== void 0 && longitude !== void 0 ? { latitude, longitude, radius_km: radius } : null,
      total_points: data?.stats?.total_points ?? null,
      cells_returned: cells.length,
      cells
    };
    return {
      content: [{ type: "text", text: JSON.stringify(snapshot, null, 2) }],
      structuredContent: snapshot
    };
  }
});

// src/lib/mcp/tools/get-jetcard.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_jetcard_default = defineTool6({
  name: "get_jetcard",
  title: "Get my JetCard",
  description: "Return the signed-in user's JetCard summary: membership status and tier, the associated merchant/venue, and the most recent account activity.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [subRes, favRes, eventRes] = await Promise.all([
      supabase.from("subscribers").select("tier, subscribed, subscription_end, cancel_at_period_end, product_id, updated_at").eq("user_id", userId).maybeSingle(),
      supabase.from("user_favorites").select("venue_id, venue_name, venue_address, venue_category, venue_neighborhood, deal_id, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(1).maybeSingle(),
      supabase.from("analytics_events").select("event_name, page_path, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(1).maybeSingle()
    ]);
    const firstError = subRes.error ?? favRes.error ?? eventRes.error;
    if (firstError) {
      return { content: [{ type: "text", text: firstError.message }], isError: true };
    }
    const sub = subRes.data;
    const fav = favRes.data;
    let merchant = null;
    if (fav?.deal_id) {
      const { data: deal } = await supabase.from("deals").select("id, merchant_id, venue_id, venue_name, venue_address, title, active, expires_at").eq("id", fav.deal_id).maybeSingle();
      if (deal) {
        merchant = {
          merchant_id: deal.merchant_id,
          venue_id: deal.venue_id,
          venue_name: deal.venue_name,
          venue_address: deal.venue_address,
          latest_deal: { id: deal.id, title: deal.title, active: deal.active, expires_at: deal.expires_at }
        };
      }
    }
    if (!merchant && fav) {
      merchant = {
        merchant_id: null,
        venue_id: fav.venue_id,
        venue_name: fav.venue_name,
        venue_address: fav.venue_address,
        latest_deal: null
      };
    }
    const lastActivityCandidates = [
      eventRes.data ? { type: eventRes.data.event_name, at: eventRes.data.created_at, page_path: eventRes.data.page_path } : null,
      fav ? { type: "favorite_saved", at: fav.created_at, page_path: null } : null
    ].filter(Boolean);
    lastActivityCandidates.sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime());
    const jetcard = {
      user_id: userId,
      email: ctx.getUserEmail(),
      status: sub?.subscribed ? "active" : "free",
      tier: sub?.tier ?? "JET",
      renews_or_ends_at: sub?.subscription_end ?? null,
      cancel_at_period_end: sub?.cancel_at_period_end ?? false,
      merchant,
      last_activity: lastActivityCandidates[0] ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(jetcard, null, 2) }],
      structuredContent: { jetcard }
    };
  }
});

// src/lib/mcp/tools/configure-notifications.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var PREF_COLUMNS = "notifications_enabled, email_notifications_enabled, background_tracking_enabled, location_tracking_enabled, auto_reload_updates, updated_at";
var configure_notifications_default = defineTool7({
  name: "configure_notifications",
  title: "Configure notifications",
  description: "Read or change the signed-in user's notification settings. Call with no arguments to read current settings; pass any of push_enabled, email_enabled, background_location_alerts, location_tracking, or auto_reload_updates to enable/disable that type.",
  inputSchema: {
    push_enabled: z6.boolean().optional().describe("Master switch for in-app/device push notifications."),
    email_enabled: z6.boolean().optional().describe("Email notifications (friend requests, direct messages, deal updates)."),
    background_location_alerts: z6.boolean().optional().describe("Background geofence alerts when near favorite venues (requires location tracking)."),
    location_tracking: z6.boolean().optional().describe("Foreground location tracking used for nearby deal alerts."),
    auto_reload_updates: z6.boolean().optional().describe("Automatically apply app updates when a new version is available.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const updates = {};
    if (input.push_enabled !== void 0) updates.notifications_enabled = input.push_enabled;
    if (input.email_enabled !== void 0) updates.email_notifications_enabled = input.email_enabled;
    if (input.background_location_alerts !== void 0)
      updates.background_tracking_enabled = input.background_location_alerts;
    if (input.location_tracking !== void 0) updates.location_tracking_enabled = input.location_tracking;
    if (input.auto_reload_updates !== void 0) updates.auto_reload_updates = input.auto_reload_updates;
    if (updates.background_tracking_enabled === true && updates.location_tracking_enabled === void 0) {
      updates.location_tracking_enabled = true;
    }
    if (updates.location_tracking_enabled === false) {
      updates.background_tracking_enabled = false;
    }
    if (Object.keys(updates).length > 0) {
      const { error: error2 } = await supabase.from("user_preferences").upsert({ user_id: userId, ...updates }, { onConflict: "user_id" });
      if (error2) {
        return { content: [{ type: "text", text: error2.message }], isError: true };
      }
    }
    const { data, error } = await supabase.from("user_preferences").select(PREF_COLUMNS).eq("user_id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const settings = {
      push_enabled: data?.notifications_enabled ?? false,
      email_enabled: data?.email_notifications_enabled ?? false,
      background_location_alerts: data?.background_tracking_enabled ?? false,
      location_tracking: data?.location_tracking_enabled ?? false,
      auto_reload_updates: data?.auto_reload_updates ?? false,
      updated_at: data?.updated_at ?? null,
      changed: Object.keys(updates).length > 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(settings, null, 2) }],
      structuredContent: { settings }
    };
  }
});

// src/lib/mcp/tools/list-activity.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var list_activity_default = defineTool8({
  name: "list_activity",
  title: "List my recent JetCard activity",
  description: "Return the signed-in user's recent JetCard activity \u2014 saved and removed favorites, shared deals, and venue reviews \u2014 each with a timestamp, venue, and action, newest first.",
  inputSchema: {
    limit: z7.number().int().min(1).max(100).default(20).describe("Maximum activities to return."),
    since_hours: z7.number().int().min(1).max(24 * 90).optional().describe("Only include activity from the last N hours (default: no time limit).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, since_hours }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const since = since_hours ? new Date(Date.now() - since_hours * 36e5).toISOString() : null;
    const withSince = (q, col) => since ? q.gte(col, since) : q;
    const [favRes, shareRes, reviewRes] = await Promise.all([
      withSince(
        supabase.from("user_favorites").select("created_at, venue_id, venue_name, deal_id").eq("user_id", userId).order("created_at", { ascending: false }).limit(limit),
        "created_at"
      ),
      withSince(
        supabase.from("deal_shares").select("shared_at, deal_id, deals(venue_id, venue_name, title)").eq("user_id", userId).order("shared_at", { ascending: false }).limit(limit),
        "shared_at"
      ),
      withSince(
        supabase.from("venue_reviews").select("created_at, venue_id, venue_name, rating, review_text").eq("user_id", userId).order("created_at", { ascending: false }).limit(limit),
        "created_at"
      )
    ]);
    const firstError = favRes.error ?? shareRes.error ?? reviewRes.error;
    if (firstError) {
      return { content: [{ type: "text", text: firstError.message }], isError: true };
    }
    const activities = [];
    for (const row of favRes.data ?? []) {
      activities.push({
        timestamp: row.created_at,
        action: "favorite_saved",
        venue_id: row.venue_id ?? null,
        venue_name: row.venue_name ?? null,
        details: row.deal_id ? `Saved from deal ${row.deal_id}` : "Saved venue"
      });
    }
    for (const row of shareRes.data ?? []) {
      const deal = row.deals;
      activities.push({
        timestamp: row.shared_at,
        action: "deal_shared",
        venue_id: deal?.venue_id ?? null,
        venue_name: deal?.venue_name ?? null,
        details: deal?.title ? `Shared deal: ${deal.title}` : "Shared a deal"
      });
    }
    for (const row of reviewRes.data ?? []) {
      activities.push({
        timestamp: row.created_at,
        action: "venue_reviewed",
        venue_id: row.venue_id ?? null,
        venue_name: row.venue_name ?? null,
        details: `Rated ${row.rating}/5${row.review_text ? `: ${row.review_text}` : ""}`
      });
    }
    activities.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    const results = activities.slice(0, limit);
    return {
      content: [
        {
          type: "text",
          text: results.length ? JSON.stringify(results, null, 2) : "No recent activity found for this account."
        }
      ],
      structuredContent: { activities: results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/list-my-venues.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var list_my_venues_default = defineTool9({
  name: "list_my_venues",
  title: "List my venues and deals",
  description: "Return every venue and deal associated with the signed-in user's account \u2014 saved favorites (venues and deals), reviewed venues, and shared deals \u2014 grouped by venue with the reason for each association.",
  inputSchema: {
    include: z8.enum(["all", "favorites", "reviews", "shares"]).default("all").describe("Which associations to include."),
    active_deals_only: z8.boolean().default(false).describe("Only include deals that are currently active and not expired."),
    limit: z8.number().int().min(1).max(200).default(50).describe("Maximum venues to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include, active_deals_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const want = (kind) => include === "all" || include === kind;
    const dealSelect = "id, venue_id, venue_name, venue_address, title, deal_type, active, starts_at, expires_at";
    const [favRes, reviewRes, shareRes] = await Promise.all([
      want("favorites") ? supabase.from("user_favorites").select(
        `created_at, venue_id, venue_name, venue_address, venue_category, venue_neighborhood, deal_id, deals(${dealSelect})`
      ).eq("user_id", userId).order("created_at", { ascending: false }).limit(200) : Promise.resolve({ data: [], error: null }),
      want("reviews") ? supabase.from("venue_reviews").select("created_at, venue_id, venue_name, rating").eq("user_id", userId).order("created_at", { ascending: false }).limit(200) : Promise.resolve({ data: [], error: null }),
      want("shares") ? supabase.from("deal_shares").select(`shared_at, deal_id, deals(${dealSelect})`).eq("user_id", userId).order("shared_at", { ascending: false }).limit(200) : Promise.resolve({ data: [], error: null })
    ]);
    const firstError = favRes.error ?? reviewRes.error ?? shareRes.error;
    if (firstError) {
      return { content: [{ type: "text", text: firstError.message }], isError: true };
    }
    const now = Date.now();
    const byVenue = /* @__PURE__ */ new Map();
    const entryFor = (venueId, venueName) => {
      const key = venueId ?? venueName ?? "unknown";
      let entry = byVenue.get(key);
      if (!entry) {
        entry = {
          venue_id: venueId,
          venue_name: venueName,
          venue_address: null,
          category: null,
          neighborhood: null,
          associations: [],
          deals: [],
          last_interaction_at: null
        };
        byVenue.set(key, entry);
      }
      return entry;
    };
    const touch = (entry, association, at) => {
      if (!entry.associations.includes(association)) entry.associations.push(association);
      if (at && (!entry.last_interaction_at || at > entry.last_interaction_at)) {
        entry.last_interaction_at = at;
      }
    };
    const addDeal = (entry, deal, source) => {
      if (active_deals_only) {
        const expired = deal.expires_at ? new Date(deal.expires_at).getTime() < now : false;
        if (deal.active !== true || expired) return;
      }
      if (entry.deals.some((d) => d.id === deal.id)) return;
      entry.deals.push({
        id: deal.id,
        title: deal.title,
        deal_type: deal.deal_type,
        active: deal.active,
        starts_at: deal.starts_at,
        expires_at: deal.expires_at,
        source
      });
    };
    for (const row of favRes.data ?? []) {
      const deal = row.deals;
      const entry = entryFor(row.venue_id ?? deal?.venue_id ?? null, row.venue_name ?? deal?.venue_name ?? null);
      entry.venue_address ??= row.venue_address ?? deal?.venue_address ?? null;
      entry.category ??= row.venue_category ?? null;
      entry.neighborhood ??= row.venue_neighborhood ?? null;
      touch(entry, deal ? "favorite_deal" : "favorite_venue", row.created_at);
      if (deal) addDeal(entry, deal, "favorite");
    }
    for (const row of reviewRes.data ?? []) {
      const entry = entryFor(row.venue_id ?? null, row.venue_name ?? null);
      touch(entry, "reviewed", row.created_at);
    }
    for (const row of shareRes.data ?? []) {
      const deal = row.deals;
      if (!deal) continue;
      const entry = entryFor(deal.venue_id ?? null, deal.venue_name ?? null);
      entry.venue_address ??= deal.venue_address ?? null;
      touch(entry, "shared_deal", row.shared_at);
      addDeal(entry, deal, "shared");
    }
    const venues = Array.from(byVenue.values()).sort((a, b) => (b.last_interaction_at ?? "").localeCompare(a.last_interaction_at ?? "")).slice(0, limit);
    const dealCount = venues.reduce((sum, v) => sum + v.deals.length, 0);
    return {
      content: [
        {
          type: "text",
          text: venues.length ? JSON.stringify(venues, null, 2) : "No venues or deals are associated with this account yet."
        }
      ],
      structuredContent: { venues, venue_count: venues.length, deal_count: dealCount }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.1";
var whoami_default = defineTool10({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in JET-Around user's profile summary. Useful to verify the connection works.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, display_name, bio, avatar_url").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = { ...data ?? {}, email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "flvhduntedvorikonuvy";
var mcp_default = defineMcp({
  name: "jet-around",
  title: "JET-Around",
  version: "0.1.0",
  instructions: "Tools for JET-Around, a Charlotte, NC nightlife and deal discovery app. Use `list_deals` to find active deals, `list_favorites` / `save_favorite` / `remove_favorite` to manage the signed-in user's saved venues, `list_my_venues` for every venue and deal associated with the account (favorites, reviews, shares) grouped by venue, `get_heatmap_density` for the latest anonymized crowd-density snapshot by time range and location, `get_jetcard` for the signed-in user's JetCard (membership status, associated merchant, last activity), `configure_notifications` to read or change the user's push/email notification settings, `list_activity` for the user's recent JetCard activity (timestamp, venue, action), and `whoami` to confirm the connected account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_deals_default,
    list_favorites_default,
    save_favorite_default,
    remove_favorite_default,
    heatmap_density_default,
    get_jetcard_default,
    configure_notifications_default,
    list_activity_default,
    list_my_venues_default,
    whoami_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
