// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-deals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-deals.ts
var list_deals_default = defineTool({
  name: "list_deals",
  title: "List active deals",
  description: "List currently active JET-Around deals in Charlotte, NC, optionally filtered by a text search over the title, description, or venue name.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional text to match against deal title, description, or venue name."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of deals to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    let query = supabase.from("deals").select("id, title, description, deal_type, venue_name, venue_address, starts_at, expires_at, website_url").eq("active", true).lte("starts_at", nowIso).gte("expires_at", nowIso).order("expires_at", { ascending: true }).limit(limit ?? 20);
    if (search) {
      const term = search.replace(/[%,]/g, " ").trim();
      query = query.or(
        `title.ilike.%${term}%,description.ilike.%${term}%,venue_name.ilike.%${term}%`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { deals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_favorites_default = defineTool2({
  name: "list_favorites",
  title: "List my saved venues",
  description: "List the venues and deals the signed-in user has saved to their JET-Around favorites.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum number of favorites to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_favorites").select("id, venue_id, venue_name, venue_address, venue_category, venue_neighborhood, deal_id, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-favorite.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var save_favorite_default = defineTool3({
  name: "save_favorite",
  title: "Save a venue to favorites",
  description: "Save a venue (and optionally a specific deal) to the signed-in user's JET-Around favorites.",
  inputSchema: {
    venue_id: z3.string().trim().describe("Identifier of the venue to save."),
    venue_name: z3.string().trim().describe("Display name of the venue."),
    venue_address: z3.string().trim().optional().describe("Street address of the venue."),
    venue_category: z3.string().trim().optional().describe("Category such as food, drink, nightlife, or events."),
    deal_id: z3.string().uuid().optional().describe("Optional deal id to associate with this favorite.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_favorites").insert({ ...input, user_id: ctx.getUserId() }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved ${input.venue_name} to favorites.` }],
      structuredContent: { favorite: data }
    };
  }
});

// src/lib/mcp/tools/remove-favorite.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var remove_favorite_default = defineTool4({
  name: "remove_favorite",
  title: "Remove a saved venue",
  description: "Remove a saved venue from the signed-in user's JET-Around favorites by favorite id or venue id.",
  inputSchema: {
    favorite_id: z4.string().uuid().optional().describe("Id of the favorite row to remove."),
    venue_id: z4.string().trim().optional().describe("Venue id to remove from favorites when the favorite id is unknown.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ favorite_id, venue_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!favorite_id && !venue_id) {
      return { content: [{ type: "text", text: "Provide favorite_id or venue_id." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("user_favorites").delete().eq("user_id", ctx.getUserId());
    query = favorite_id ? query.eq("id", favorite_id) : query.eq("venue_id", venue_id);
    const { data, error } = await query.select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Removed ${data?.length ?? 0} favorite(s).` }],
      structuredContent: { removed: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in JET-Around user's profile summary. Useful to verify the connection works.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, display_name, bio, avatar_url").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = { ...data ?? {}, email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "flvhduntedvorikonuvy";
var mcp_default = defineMcp({
  name: "jet-around",
  title: "JET-Around",
  version: "0.1.0",
  instructions: "Tools for JET-Around, a Charlotte, NC nightlife and deal discovery app. Use `list_deals` to find active deals, `list_favorites` / `save_favorite` / `remove_favorite` to manage the signed-in user's saved venues, and `whoami` to confirm the connected account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_deals_default, list_favorites_default, save_favorite_default, remove_favorite_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
